"fier-eclaireur" ;     (* Akim envoie Onterberg et Lucrèce sous la Brume. *)
"deuil" ;              (* Alexandre retrouve Isidora chez Najah. *)
"suicide" ;            (* Sébastien convainc Giselle de tuer un membre de 
			  l'équipage. *)
"envol" ;              (* Simmera rencontre Giselle à bord du Tyran Boréal. *)
"presses" ;            (* Saïar parle à Nathan des actions d'Orona à Hayako. *)
"la-meute" ;           (* Galilée vient se plaindre à Akim des filles du 
		          cauchemar. *)
"transaction" ;        (* Nathan rencontre Carnaval, lui vend des fusées, 
			  récupère une commande et une gorgone. *)
"fusees" ;             (* Le Tyran Boréal est détruit. *)
"naufrage" ;           (* Simmera atterrit en rase campagne. *)
"ambition" ;           (* Akim rencontre Orthys, parle d'Orona. *)
"esclaves" ;           (* Nathan rencontre Orona à Virnalvir. *)
"ordo-aureus" ;        (* Staniel exécute Akim et nomme Hans Banach à sa 
			  place. *)
"exploration" ;        (* Onterberg et Lucrèce arrivent au fond du monde. *)
"fantomes" ;           (* Simmera rencontre les naufragés. *)
"affranchie" ;	       (* Simmera libère Géraldine. *)
"hayako" ;             (* Staniel parle à Hayako. *)
"dernier-temple" ;     (* Simmera arrive au Dernier Temple. *)
"triangle" ;           (* Staniel, Julie et Simmera parlent de leurs 
			  projets. *)
"romance" ;            (* Giselle rencontre Charles et Eusèbe. *)
"isidora" ;            (* Le Conseil fait prêter serment à Isidora. *)
"trahison" ;           (* Carnaval interroge Nathan sur Giselle. *) 
"insurrection" ;       (* Giselle prend le contrôle des Altarane. *)
"exorcisme" ;          (* Julie emmène Simmera à Nymett. *)
"lovecraft" ;          (* Les Suidinns attaquent ! *)
"maya" ;               (* Simmera parle avec Maya. *)
"hedris" ;             (* Simmera et Julie enquêtent à Hédris. *)
"demi-vie" ;           (* Fin de l'aventure à Hédris. *)
"relique" ;            (* Nathan tue Maya, parle à Than. *)
"jouldari" ;           (* Morgane accueille Carnaval à Nymett. *)
"nymett" ;             (* Nathan et Carnaval trompent Simmera. *)
"kirons" ;             (* Julie invoque une Kiron, Simmera retrouve 
                          Giselle. *)
"rituel" ;             (* Ildaric et Hayako parlent de l'invasion. *)
"survol" ;             (* Simmera arrive à Hayako. *)
"rencontre" ;          (* Simmera parle avec Orona et Ildaric. *)

(* Ildaric explique à Simmera les Suidaster. *)

"nathan-vs-thanadir" ; (* Nathan tue Julie. *)
"nouvelle-thanadir" ;  (* Simmera devient la nouvelle Thanadir. *)
"the-end" ;            (* Simmera tue Ildaric et Orona définitivement. *)
